server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?useSSL=false
    username: root
    password: zongshuai
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
