server:
  port: 8010
spring:
    datasource:
      username: root
      password: rootzs
      url: jdbc:mysql://localhost:3306/transDemo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package:  com.zshuai.pojo
logging:
  config: classpath:log4j2-spring.xml 